# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: src/proto/speech.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import src.proto.speech_pb2


class SpeechServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Say(self, stream: 'grpclib.server.Stream[src.proto.speech_pb2.SayRequest, src.proto.speech_pb2.SayResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/viamlabs.service.speech.v1.SpeechService/Say': grpclib.const.Handler(
                self.Say,
                grpclib.const.Cardinality.UNARY_UNARY,
                src.proto.speech_pb2.SayRequest,
                src.proto.speech_pb2.SayResponse,
            ),
        }


class SpeechServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Say = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.speech.v1.SpeechService/Say',
            src.proto.speech_pb2.SayRequest,
            src.proto.speech_pb2.SayResponse,
        )
